CREATE DATABASE IF NOT EXISTS feeds;
USE feeds;

CREATE TABLE IF NOT EXISTS posted_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  guid VARCHAR(255) UNIQUE NOT NULL,
  posted_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
